-- 0016 — a claim token on the three eventing queues, so a late acknowledgement
-- from a worker that lost its claim can be refused instead of applied (B-26).
--
-- What is still broken after B-22, B-24 and B-25. A claim is a write, so two
-- workers cannot claim the same row at the same instant. `claimed_at` says a
-- worker holds the row, and `reclaims` bounds how often it may be taken back. All
-- three are about the moment of claiming. None of them says anything about the
-- interval *after* the claim, and that is where the remaining defect lives:
--
--   1. worker A claims row R, lease 30s, and stalls — GC pause, blocked syscall,
--      a slow HTTP call to a subscriber;
--   2. the lease expires, recovery frees R, worker B claims it and publishes it;
--   3. worker A wakes up and calls markPublished / markProcessed / markDelivered
--      on R. The statement names the row and nothing else, so it applies.
--
-- A's acknowledgement describes an attempt that was abandoned. It overwrites B's
-- result: A's `last_error`, A's status, and — for a delivery — a `last_status`
-- from a response B never received. Two attempts happened and the row records
-- the wrong one. `core_worker_outcomes_total{outcome="fenced"}` exists in the
-- catalogue precisely to count this refusal, and for three of the four workers it
-- could never be anything but zero, because there was nothing to refuse with.
--
-- The fix. `claim_token text`, stamped fresh by `claimDue` and cleared by every
-- acknowledgement and by recovery. Each acknowledgement carries the token it was
-- given and matches on it, so A's late call matches no row and is reported as
-- `fenced` rather than applied. This is the shape `notification` has had since
-- migration 0012; the other three queues are being brought up to it rather than
-- given anything new.
--
-- Why text and not uuid. `notification.claim_token` is `text`, and one type for
-- one concept across four queues is worth more than four bytes a row. The value
-- is a v4 UUID generated by the application, so the domain clock and the tests
-- stay in control of it.
--
-- No index. The token is only ever read as an extra predicate on a statement that
-- already names the row by primary key.
--
-- Every statement below is written to be re-runnable (`IF NOT EXISTS`, and a
-- guarded drop before each ADD CONSTRAINT, since Postgres has no
-- `ADD CONSTRAINT IF NOT EXISTS`). A migration that records itself should never
-- run twice, but one that cannot survive running twice turns any interrupted
-- deploy into a manual repair before the next one can proceed.
--
-- The constraint, and the direction it is asserted in. A token may only exist on
-- a row somebody is holding: `claim_token is null or claimed_at is not null`. The
-- opposite direction — every claimed row must carry a token — is the stronger
-- invariant and is deliberately NOT asserted, because it is false for rows that
-- were already claimed when this migration runs. Those rows were claimed by code
-- that had no token to write, and they are not corrupt: recovery will free them
-- and the next claim will stamp one. Asserting the stronger form would either
-- fail the migration or force a backfill, and a backfilled token would fence the
-- acknowledgement of a worker that is at that moment still doing real work.
--
-- Deploying it. Existing rows get null, meaning "no token held". During the
-- window where this migration is applied and the old code is still running, that
-- old code acknowledges without mentioning the token: those statements still
-- match, so nothing is refused and nothing breaks — the fence simply is not in
-- force yet for claims taken before the deploy. Rolling back is the reverse order:
-- roll the code back first, then this migration, because code that writes
-- `claim_token` against a schema without the column fails every claim.

BEGIN;

ALTER TABLE outbox ADD COLUMN IF NOT EXISTS claim_token text;
ALTER TABLE outbox DROP CONSTRAINT IF EXISTS outbox_claim_token_check;
ALTER TABLE outbox
    ADD CONSTRAINT outbox_claim_token_check
    CHECK (claim_token IS NULL OR claimed_at IS NOT NULL);

ALTER TABLE inbound_event ADD COLUMN IF NOT EXISTS claim_token text;
ALTER TABLE inbound_event DROP CONSTRAINT IF EXISTS inbound_event_claim_token_check;
ALTER TABLE inbound_event
    ADD CONSTRAINT inbound_event_claim_token_check
    CHECK (claim_token IS NULL OR claimed_at IS NOT NULL);

ALTER TABLE event_delivery ADD COLUMN IF NOT EXISTS claim_token text;
ALTER TABLE event_delivery DROP CONSTRAINT IF EXISTS event_delivery_claim_token_check;
ALTER TABLE event_delivery
    ADD CONSTRAINT event_delivery_claim_token_check
    CHECK (claim_token IS NULL OR claimed_at IS NOT NULL);

INSERT INTO schema_migrations (version) VALUES ('0016_worker_claim_fencing')
ON CONFLICT (version) DO NOTHING;

COMMIT;
